server:
  port: 19000

spring:
  profiles:
    active: native
    group:
      prod: prod
  application:
    name: config-server
  cloud:
    bus:
      destination: banking-platform.dev.event.config-event.json
    config:
      server:
        native:
          search-locations: classpath:/config-repo
          watch:
            enabled: true
  kafka:
    bootstrap-servers: http://loacalhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "refresh, busrefresh, *"
  endpoint:
    health:
      show-details: always